// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS3EJxsI497E4i7T0HG7sig2uIqzI2kcU',
    appId: '1:215817033589:web:491107399e080df1d2a53c',
    messagingSenderId: '215817033589',
    projectId: 'fsd-mwwm-mobx-demo',
    authDomain: 'fsd-mwwm-mobx-demo.firebaseapp.com',
    storageBucket: 'fsd-mwwm-mobx-demo.firebasestorage.app',
    measurementId: 'G-0F8L4EJ0SG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxP8yWIUx7bfh-2tiZAIzFJjhtWQC_p_I',
    appId: '1:215817033589:android:25178627bd0e1062d2a53c',
    messagingSenderId: '215817033589',
    projectId: 'fsd-mwwm-mobx-demo',
    storageBucket: 'fsd-mwwm-mobx-demo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIecM_quFofexYU5WddbaC-CmNVVnC08o',
    appId: '1:215817033589:ios:90343d41120034bad2a53c',
    messagingSenderId: '215817033589',
    projectId: 'fsd-mwwm-mobx-demo',
    storageBucket: 'fsd-mwwm-mobx-demo.firebasestorage.app',
    iosBundleId: 'com.example.fsdMwwmMobxDemo',
  );
}
